steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/appdocente-453515/rag-docente:latest',
      '.'
    ]
images:
  - 'gcr.io/appdocente-453515/rag-docente:latest'